### ISSUE TITLE
Confusion about wikijs configuration and setup in docker container

### ISSUE THREAD

**Issue by pdavis68** [Requarks/wiki-v1#119]
I'm using Docker for Windows... Using the example provide here:

https://github.com/Requarks/wiki/blob/master/tools/docker-compose.yml

I seem to have issues with my volumes. For example, 
`./config.yml:/var/wiki/config.yml`
would presumably map the config.yml in the directory from where I'm executing `docker-compose up` to the /var/wiki directory in my docker container. But there is no wiki directory under my /var directory.

So, this is my docker-compose.yml that I actually use. I've tried replacing `./` with `//./` but that doesn't address my issues...

```
version: '3'
services:

  wikidb:
    image: mongo:3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: expassword 
      
    volumes:
        - /mongo/data/db:/data/db
        - ./data/mongod.conf:/etc/mongod.conf
        
  wikijs:
    image: 'requarks/wiki:latest'
    links:
      - wikidb
    depends_on:
      - wikidb
    ports:
      - '1081:3000'
    environment:
      WIKI_ADMIN_EMAIL: myemail@gmail.com
    volumes:
      - ./config.yml:/var/wiki/config.yml        
      - ./logs:/logs
```

From the directory where I run `docker-compose up`...

If I run with `./`, I get no mongod.conf in my etc folder. I get no /logs folder in my root. 

I do have the mongo volume that I've created separately, outside of all this and that's used properly....

Now, if I replace './' with '//./', in the container, I get a /data directory in the root with a mongod.conf directory, but not the actual mongod.conf file which is my host data directory. And obviously, it's backwards. It should be mongod.conf in the etc folder, not in the data folder.

What's going on? How do I straighten this all out?
Thanks
