### ISSUE TITLE
Not pushing to git?

### ISSUE THREAD

**Issue by madchap** [Requarks/wiki-v1#129]
Using latest docker image, through docker-compose. Site works fine.

### Actual behavior
Upon saving, nothing gets pushed.
Nothing in the container logs.

If I exec into the container, git works (eventually after a `git pull --allow-unrelated-histories`), I can `git push` and all. Local git changes are well there, as a `git log` can attest.

There seems to be no action whatsoever with git backend.

```
git:                                                                                                                           
  url: git@gitlab.com:myrepo/wikijs.git
  branch: master               
  auth: 
        
    # Type: basic or ssh
    type: ssh          
        
    # Only for SSH authentication:
    privateKey: /etc/wiki/keys/git.pem
        
    sslVerify: true  
        
  # Default email to use as commit author
  serverEmail: xxxxxxx@gmail.com
        
  # Whether to use user email as author in commits
  showUserEmail: true  
        
  signature:         
    name: Fred Blaise
    email: xxxxxxx@gmail.com
```

### Expected behavior
Upon saving, my changes are pushed.
