### ISSUE TITLE
Example docker-compose should not use links

### ISSUE THREAD

**Issue by JanoschDeurer** [Requarks/wiki-v1#201]
The example docker-compose file on https://github.com/Requarks/wiki-v1/blob/master/tools/docker-compose.yml uses links. Links are deprecated [(Docker links)](https://github.com/Requarks/wiki-v1/blob/master/tools/docker-compose.yml) and should no longer be used. They are also no longer necessary, I used the following docker-compose to get it running:

```
version: '2'
services:
  wikidb:
    image: mongo:3
    expose:
      - '27017'
    command: '--smallfiles --bind_ip ::,0.0.0.0'
    environment:
      - 'MONGO_LOG_DIR=/dev/null'
    volumes:
      - ./volumes/mongo:/data/db
  wikijs:
    image: 'requarks/wiki:latest'
    depends_on:
      - wikidb
    ports:
      - '8084:80'
    environment:
      WIKI_ADMIN_EMAIL: admin@example.com
    volumes:
      - ./volumes/config.yml:/var/wiki/config.yml

```
