### ISSUE TITLE
Error when uploading image: "Unable to fetch updated listing."

### ISSUE THREAD

**Issue by dsat2002** [Requarks/wiki-v1#47]
### Actual behavior
Edit page -> insert image -> upload image -> "upload complete" -> "unable to fetch updated listing"

uploading the same image results in "file exists" where it does exist in ../wiki_repo/uploads/image.jpg

### Expected behavior
Edit page -> insert image -> upload image -> "upload complete" -> ability to select uploaded image to insert

### Steps to reproduce the behavior
upload an image

read and write permissions exist

- wiki ver 1.0.11
- node v8.9.1
- windows server 2012

**Comment by bijeesraj** [comment]
Same issue here.

**Comment by JanoschDeurer** [comment]
> @kopax Development is being done on the [dev](https://github.com/Requarks/wiki/commits/dev) branch (2.0 version), which has new commits every week. No new updates are being released for the 1.x version unless a critical bug is found.

Isn't that a critical bug? I think when the image upload is not working it makes the wiki unusable.

**Comment by NGPixel** [comment]
> Isn't that a critical bug? I think when the image upload is not working it makes the wiki unusable.

No as it is working fine for most people. Trying to fix all the upload issues for all possible setups would take too much time... Time that would be better spent on v2.

**Comment by JanoschDeurer** [comment]
Thank you for the fast response. We have a setup with docker-compose and your docker image. So it should be fairly standard. Should I open a new ticket that this is also not working in a basic docker-compose installation?

I would really like using wikijs, I think it has wonderful features and a really good software stack. However, this bug is making it unusable for me, also deactivating MathJax did not work for me.

**Comment by Sv3n** [comment]
> > Isn't that a critical bug? I think when the image upload is not working it makes the wiki unusable.
> 
> No as it is working fine for most people. Trying to fix all the upload issues for all possible setups would take too much time... Time that would be better spent on v2.

If it is working for most people, then it should be possible to determine the factor that breaks it for some.

Asking this in general to everyone: Is there a setup you know of, using docker-compose or otherwise, in which the upload feature of  wikijs-v1 works? All my efforts so far have had the same (non-working) result. If so: can you please describe it, or perhaps point out the differences with my setup as shown below?

My (non-working) setup:
```
Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-45-generic x86_64)

root@machine:~/wikijs# docker --version
Docker version 18.06.1-ce, build e68fc7a

root@machine:~/wikijs# uname -a
Linux machine 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

root@machine:~/wikijs# docker images
REPOSITORY                                                    TAG                 IMAGE ID            CREATED             SIZE
mongo                                                         3                   b2f40c62a495        2 days ago          431MB
requarks/wiki                                                 latest              85e4f332eda3        3 months ago        315MB
```

```
root@machine:~/wikijs# cat docker-compose.yml

version: '3'
services:
  wikidb:
    image: mongo:3
    expose:
      - '27017'
    command: '--smallfiles --bind_ip ::,0.0.0.0'
    environment:
      - 'MONGO_LOG_DIR=/dev/null'
    volumes:
      - ./data/mongo:/data/db
  wikijs:
    image: 'requarks/wiki:latest'
    links:
      - wikidb
    depends_on:
      - wikidb
    ports:
      - '8089:3000'
    environment:
      WIKI_ADMIN_EMAIL: admin@example.com
    volumes:
      - /root/wikijs/cfg.yml:/var/wiki/config.yml
```

Wiki config, shortened: removed all commented settings, and all external auth options are disabled.
Removed git-section (both with and without a valid git repo config, the upload feature behaves the same).

```
root@machine:~/wikijs# cat cfg.yml
# Wiki config:
# shortened: removed all commented settings, and all external auth options are disabled
# removed git-section (both with and without a valid git repo config, the upload behaviour is the same)
title: Wiki
port: 3000

paths:
  repo: ./repo
  data: ./data

uploads:
  maxImageFileSize: 30
  maxOtherFileSize: 100

lang: en

# Enable for right to left languages (e.g. arabic):
langRtl: false

public: false

sessionSecret: 1234567890abcdefghijklmnopqrstuvxyz

db: mongodb://wikidb:27017/wiki

features:
  linebreaks: false
  mathjax: false

externalLogging:
  bugsnag: false
  loggly: false
  papertrail: false
  rollbar: false
  sentry: false

theme:
  primary: indigo
  alt: blue-grey
  viewSource: all # all | write | false
  footer: blue-grey
  code:
    dark: true
    colorize: true
```

Text emitted on the console while running docker-compose:

[console.txt](https://github.com/Requarks/wiki-v1/files/3126364/console.txt)

Logs from within the running container (also showing some of the files present after a failed upload (file appears in the git repo, but post-pressing seems to fail):

[in_container_logs.txt](https://github.com/Requarks/wiki-v1/files/3126363/in_container_logs.txt)
Shows errors related to the not-configured git repo. My other test (with valid git config) did not show these errors, so they are unrelated to the problem at hand.

Thank you for your time! :)
