### ISSUE TITLE
LDAP users always created read only

### ISSUE THREAD

**Issue by szmoore** [Requarks/wiki-v1#60]
### Actual behavior
When the only authentication method is LDAP, users can login but no users can write any pages.
Searching mongodb manually shows they are all read-only access.

### Expected behavior
For configurations where the authentication is only LDAP, then there should be a way to either have an administrator, or have all users default to write access.

### Steps to reproduce the behavior
Use LDAP as the authentication mechanism.
```
auth:
  # Has no effect
  defaultReadAccess: false
  ldap:
     enabled: true
     url: ldap://etcetera
     bindDn: CN=Reader,CN=Users,DC=site,DC=com
     bindCredentials: ....
     searchBase: CN=Users,DC=site,DC=com
     searchFilter: (&objectClass=user)(sAMAccountname={{username}}))
     tlsEnabled: false
```

## Work Around:
On database server run:

```
mongo wiki --eval 'db.users.update({"rights.0.role" : "read"}, {$set : {"rights.0.role" : "write"}}, {multi:true})
```
